### ISSUE TITLE
Пүрвээ нэмэлт ажил

### ISSUE THREAD

**Issue by Sergelen83** [Purewee/caak-front#143]
- [x] **Таг хуудсан дээр Сторинуудыг харуулах**
   - Тухайн тагаар нь шүүгээд тэр таг дээр байгаа сторинуудыг үүн шиг харуулах
![ыбөхыбөхбыөх](https://github.com/Purewee/caak-front/assets/84310638/9c126bb8-f99b-4a4d-978f-101fdb0082cd)

- [x] А1 баннерын хэмжээг **1900х300** болгож өөрчлөх
![sdfhdfhdfghfdghfgh](https://user-images.githubusercontent.com/84310638/235633390-ec962833-6a61-46bb-bb03-7e79f5e2df3c.JPG)

- [x] А3 баннер өөрчлөгдсөнтэй холбоотой харагдах хэсэг, хэмжээ эд нарыг дараах байдлаар өөрчлөх
  - Хэмжээг ийм болгох: **760х390**
  - Текстийг ингэж өөрчлөлт: **"Мэдээг дэлгэрэнгүй үзэх үед мэдээн дунд таны баннер том хэмжээтэй, хүртээмжтэй байршилд харагдах болно"**
![555gbggg](https://user-images.githubusercontent.com/84310638/235622037-6a16aff8-74b3-48cb-93ca-21ae76b29ecb.JPG)
  - Жишээ баннер харах:
    - 1. @boldush45 харагдах байдлыг шинэ А3 баннер хэрхэн харагдах байдлаар энэ хэсгийг өөрчлөх
    - 2. Тэр текстийг хасан, хэмжээг өөрчлөх: **760х390**
![fgfghg6777](https://user-images.githubusercontent.com/84310638/235622438-00074953-b2d3-46e5-bb34-c3206b4e32c6.JPG)

- [x] **ОНЦЛОХ МЭДЭЭ хэсгийн өөрчлөлт**
   - Текстийг ийм байдалтай харуулах: 
       - Бусад мэдээнүүдээс дэвсгэр өнгөөр харагдана
       - Сайтын бүх мэдээний дэлгэрэнгүй дунд харагадана (спонсород пост)
       - Манай сошиал сувгууд (facebook, twitter)-аар давхар шэйр хийгдэнэ
   - Жишээ үзэх: дарахад @boldush45 хийж өгөх загварыг дуудна
![fgg6777555](https://user-images.githubusercontent.com/84310638/235628289-5bf1b3c8-6248-4a23-a423-7a46ae406c0c.JPG)

- [x] **МЭДЭЭ, НИЙТЛЭЛ БЭЛТГЭХ хэсгийн Жишээ товчинд линк холбох**
    - Холбох линк: https://www.caak.mn/post/view/265692
    - шинэ таб руу үсэргээрэй
![fgy6666](https://user-images.githubusercontent.com/84310638/235628675-ce1d2570-aee9-4ed4-bb16-fefa83286645.JPG)

- [x] **Сториг онцлох болгодог болгох**
   - "Онцлох" дээр дарахад эхлэх дуусах огноо гарч ирнэ. Гэвч цаанаа онцлох гэж бүртгэж авахгүй байгаа юм билээ. 
   - Онцлох болсон стори бүх сторинуудын эхэнд огноо дуустал харагдана
![fhfgh7777](https://user-images.githubusercontent.com/84310638/235619900-4bc061e4-b0d3-404a-bf72-6683dcf51cd5.JPG)
   - Онцлох стори нь од тэмдэгтэй нүүрэн дээр харагдана. Одыг хавсаргав
![541415](https://user-images.githubusercontent.com/84310638/209102983-e11ab27a-13e5-4564-8e10-9e723fc3e632.png)
![209102812-615cb713-708f-4b96-888c-14969093cfa5](https://user-images.githubusercontent.com/84310638/235620344-a3af4f13-4cc7-4008-a6d5-63274b263a65.jpg)

**Comment by Sergelen83** [comment]
@boldush45  -оо Пүрвээ өнөөдөр орой энэ ажил дээр суух гэж байгаа тул чамайг таглаж хэлсэн дизайныг нь хурдан хийгээд өгээрэй. 
**Дараах ажлууд:**
- А3 баннерын жишээ зураг пс, мобайл дээр хэрхэн харагдах
- Онцлох мэдээний жишээ зураг
- Онцлох сторины star icon байршуулсан дизайн
-

**Comment by Sergelen83** [comment]
Энэ issue яагаад хаагдсан байдаг билээ. Шалгагдаагүй мөн дутуу тасктай. 
@boldush45 зургийг нь хийж өгсөн үү?

**Comment by boldush45** [comment]
### Таг хуудсан дээр Сторинуудыг харуулах
https://xd.adobe.com/view/f5db0ea8-36c9-4258-a87e-abf8d23e77fd-a088/screen/353dca6c-df58-451b-bb95-676ed465f950/
@Purewee @Sergelen83

**Comment by boldush45** [comment]
### **А3 баннер** 
Баннер харагдах зургийг шинэчлэв.
https://xd.adobe.com/view/f5db0ea8-36c9-4258-a87e-abf8d23e77fd-a088/screen/58df0588-3ed1-4313-b3b9-73f4c377adc4/specs/
@Purewee

**Comment by Sergelen83** [comment]
@boldush45  онцлох стори хэрхэн харагдахыг хийгээгүй үлдсэн байна. Минийх дээрх зураг шиг байршуулаад явах юм уу чи ямар байдлаар шийдэж харуулах юм. Тэр дизайныг авах хэрэг байна.

**Comment by Sergelen83** [comment]
@boldush45  **А3 харагдах дизайн** хийгдсэнг харлаа. 
Яг сэтгэлд бол хүрэхээр хэрэглэгчид баримжаа чиглэл өгөхгүй л байна. Заавал энэ пс, мобайл дээр доор харуулахыг стандартыг өөрчлөөд зэрэгцээ харуулаад явбал яасын??? 

Жишээ нь ийм байдлаар:
![FSDHSDFGH456](https://github.com/Purewee/caak-front/assets/84310638/0097fbce-3d68-4c01-9c76-5dfca4f680ac)


Жишээ нь ийм байдлаар:
